<?php
/**
 * Created by PhpStorm.
 * User: jianfenliu
 * Date: 2019/2/21
 * Time: 上午11:31
 */
class Target{
    function request(){
        echo "Target's request\r\n";
    }
}

class Adaptee{
    function specificRequest(){
        echo "specific request\r\n";
    }
}
class Adapter extends Target{
    private $adaptee;
    function __construct( Adaptee $adaptee)
    {
        $this->adaptee = $adaptee;
    }
    function request()
    {
        //parent::request(); // TODO: Change the autogenerated stub
        $this->adaptee->specificRequest();
    }
}

$adaptee = new Adaptee();
$target = new Adapter($adaptee);
$target->request();